spring.application.name=Jira
springdoc.swagger-ui.use-root-path=true
# =====================================================================
# 1. MySQL Database Connection Settings (Jira_Local_Db)
# =====================================================================
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/jira?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
# Enter your root user password below (leave empty after the '=' if you don't use a password)
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =====================================================================
# 2. Hibernate / JPA Properties
# =====================================================================
# Dialect to help Hibernate optimize SQL statements for MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Automatically updates the database schema matching your entity models
spring.jpa.hibernate.ddl-auto=update

# Enable logging to see the SQL queries executing in your console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Tell Spring to use Caffeine as the cache provider
spring.cache.type=caffeine

# Configure Cache Specs:
# tasks: keeps up to 500 records in memory, expires if untouched for 10 minutes
# comments: keeps up to 1000 records in memory, expires if untouched for 5 minutes
spring.cache.caffeine.spec=maximumSize=500,expireAfterAccess=10m

# Token config
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com